### PR TITLE
chore:(maps) add new maps

### PR DESCRIPTION
**Pull request by RadNotRed**
These are just the maps that weren't registered already that I've seen, all have images. I'll attach here as well

### CODE REVIEW

**Comment by RadNotRed** [comment]
the-core
production-yard
estates
phase-runner
wattson-pylon
zeus-station

**Comment by Holfz** [comment]
Hello, Just to notice. Don't forgot to resolve the link on the PR reviews

**Comment by RadNotRed** [comment]
> Hello, Just to notice. Don't forgot to resolve the link on the PR reviews

wdym? they're really just meant to be put into the discord application thing and names to be changed over

**Comment by Holfz** [comment]
> wdym? they're really just meant to be put into the discord application thing and names to be changed over

The image link in the [Constants/Gallery.js](https://github.com/Holfz/ApexRPC/pull/12/files/1c700e58acb1ca2c7f92ad851cb0127ea22f58ba#diff-d75e8b3b41a3dff2e9016c33b50c4afe521a29fc4f3af466337a6c3703d072de), Usually it's the image name that's hosted by the discord (I need to upload it manually to discord via Discord Developers page)

**Comment by RadNotRed** [comment]
> > wdym? they're really just meant to be put into the discord application thing and names to be changed over
> 
> The image link in the [Constants/Gallery.js](https://github.com/Holfz/ApexRPC/pull/12/files/1c700e58acb1ca2c7f92ad851cb0127ea22f58ba#diff-d75e8b3b41a3dff2e9016c33b50c4afe521a29fc4f3af466337a6c3703d072de), Usually it's the image name that's hosted by the discord (I need to upload it manually to discord via Discord Developers page)

Sure ill change them now then, if you upload them there

**Comment by Holfz** [comment]
Thank you for your contributing!

**Pull request merged**
