### PR TITLE
Added Full Ranked Support, Partial Arenas Support

### PR DESCRIPTION
**Pull request by tzunni**
Ranked is now supported fully as I found the specific `gamemode` tag it uses, and ranked just uses the same maps that public lobbies do. On the other hand, arenas (and subsequently ranked arenas) aren't fully supported because I'm having trouble implementing images (I'm new to JS haha).

### CODE REVIEW

**Comment by Holfz** [comment]
I've try refactor the code, Could you please test if it works ?

**Comment by tzunni** [comment]
`Gallery.js` seems to be missing `#mp_rr_arena_skygarden` otherwise known as Encore. 
However, the arena code doesn't seem to be loading the discord presence image at all, as it doesn't load one in for any of the four arena maps, but is functional otherwise.

**Comment by Holfz** [comment]
Ok Thanks, Will merge when image are ready (1-2 days I will do it)

**Comment by Holfz** [comment]
Sorry for a slight delay, Busy on working for some job.

The encore gallery will commit after the merge, I think the arena picture is missing for another three map, Please test the encore and tell me if it working.

**Comment by tzunni** [comment]
> Sorry for a slight delay, Busy on working for some job.
> 
> The encore gallery will commit after the merge, I think the arena picture is missing for another three map, Please test the encore and tell me if it working.

I just confirmed that Encore is working with the merge. I hadn't time to check on it earlier because of school, but thank you for your work.

**Pull request merged**
